### PR TITLE
Fix/Prevent crash on setting user as null

### LINKED ISSUE #274: Crash when querying channel
We just encountered an issue when trying to query channels.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getstream.sdk.chat.rest.User.e()' on a null object reference
       at com.getstream.sdk.chat.rest.core.Client$5.onSuccess(Client.java:747)
       at com.getstream.sdk.chat.rest.core.Client.onSetUserCompleted(Client.java:533)
       at com.getstream.sdk.chat.rest.core.Client.queryChannels(Client.java:744)
       ...
```

Seems like the User returned in `onSuccess` is null.
Earlier the `onSetUserCompleted` returned with `onSuccess` too when setting the user. And because it did I've tried to fetch the channel, and above happened :/

**SDK Version:** 3.2.0

### PR DESCRIPTION
**Pull request by bevzaanton**
# Submit a pull request

- Prevent crash on setting user as null
- close #274

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java [hunk 1]
```diff
@@ -423,14 +423,16 @@ public synchronized void setUser(User user, final TokenProvider provider, Client
      * @param user     the user to set as current
      * @param provider the Token Provider used to obtain the auth token for the user
      */
-    public synchronized void setUser(User user, final TokenProvider provider) {
-
+    public synchronized void setUser(User user, @NotNull final TokenProvider provider) {
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java]: Let's add also `@NotNull` to `user` parameter.
