### PR TITLE
Fix/Crash invalid link

### LINKED ISSUE #171: Youtube invalid link crash and preview issue
1. If I try to edit `Youtube` message with invalid link the app crashes:

```
E  FATAL EXCEPTION: main
E  Process: io.getstream.chat.sdk, PID: 15733
E  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E      at com.getstream.sdk.chat.view.MessageInputView.a(:4)
E      at f.e.a.a.b0.x.a(Unknown Source:4)
E      at androidx.lifecycle.LiveData.a(Unknown Source:29)
E      at androidx.lifecycle.LiveData.b(Unknown Source:44)
E      at androidx.lifecycle.LiveData.b(Unknown Source:14)
E      at d.m.q.b(Unknown Source:0)
E      at androidx.lifecycle.LiveData$a.run(Unknown Source:18)
E      at android.os.Handler.handleCallback(Handler.java:883)
E      at android.os.Handler.dispatchMessage(Handler.java:100)
E      at android.os.Looper.loop(Looper.java:214)
E      at android.app.ActivityThread.main(ActivityThread.java:7356)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

2. `Youtube` and `Unsplash` messages with invalid links looks differently:
Screenshot 2019-10-16 at 16 58 40
Screenshot 2019-10-16 at 17 49 35

Used `Youtube` link: https://www.youtube.com/watch?v=K0x-jSKOoR
Used `Unsplash` link: https://unsplash.com/photos/kAK7A

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request
close #171

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java [hunk 1]
```diff
@@ -257,31 +257,34 @@ private void observeUIs(LifecycleOwner lifecycleOwner) {
...
+                || message.getAttachments().isEmpty()
+                || message.getAttachments().get(0).getType().equals(ModelType.attach_giphy)
+                || message.getAttachments().get(0).getType().equals(ModelType.attach_unknown))
+            return;
+
+        for (Attachment attachment : message.getAttachments())
+            attachment.config.setUploaded(true);
+
+        if (message.getAttachments().get(0).getType().equals(ModelType.attach_file)) {
+            String fileType = message.getAttachments().get(0).getMime_type();
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: `message.getAttachments().get(0)`
Might be exacted for readability.

File: library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java [hunk 2]
```diff
@@ -257,31 +257,34 @@ private void observeUIs(LifecycleOwner lifecycleOwner) {
...
+            if (fileType.equals(ModelType.attach_mime_mov) ||
+                    fileType.equals(ModelType.attach_mime_mp4)) {
+                messageInputClient.onClickOpenSelectMediaView(null, message.getAttachments());
             } else {
-                if (!message.getAttachments().get(0).getType().equals(ModelType.attach_giphy))
-                    messageInputClient.onClickOpenSelectMediaView(null, message.getAttachments());
+                messageInputClient.onClickOpenSelectFileView(null, message.getAttachments());
             }
+        } else {
+            messageInputClient.onClickOpenSelectMediaView(null, message.getAttachments());
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: Is it correct that `MessageInputClient` is responsible for all input related logic?

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: > Is it correct that `MessageInputClient` is responsible for all input related logic?

Yeah, I think so. Attachment has several types such as `image`, `giphy`, `video`, `product`, `file`, `link` and `unknown`.

All kinds of Attachments can have image or video link except in case `giphy` and `unknown`.
I have added if statement for it.
```java
        if (message.getAttachments() == null
                || message.getAttachments().isEmpty()
                || attachment.getType().equals(ModelType.attach_giphy)
                || attachment.getType().equals(ModelType.attach_unknown))
            return;
```

Comment (elevenetc) [reply library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: Ok, `Client` part confused me actually. I would rename it to `Controller`. That's more or less common term for UI business logic entity.

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: OK, Good idea.

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: @elevenetc, Renamed to `MessageInputController`
