### PR TITLE
Fix/Edit & delete & Reaction thread parent message

### LINKED ISSUE #275: Editing parent thread message doesn't work
To reproduce:
1. Open list of channels
2. Open channel
3. Long press on a message
4. Start thread
5. Long press on a parent message
6. Select Edit
7. Edit message
8. Press send

Expected:
Message is edited
Actual:
Message is not edited

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request
close #275 , #272

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/rest/Message.java [hunk 1]
```diff
@@ -302,6 +302,7 @@ public Message copy() {
         clone.parentId = parentId;
         clone.command = command;
         clone.commandInfo = commandInfo;
+        clone.isThreadParent = isThreadParent;
```
Comment (tbarbugli) [inline library/src/main/java/com/getstream/sdk/chat/rest/Message.java]: @adrian09h the whole `isThreadParent`, `isThreadParent()` and `setThreadParent` does not make any sense. You can tell a message is the parent of a thread because it is returned by the API with `parent_id` set to `null`. All this extra fields and setters are there to create bugs

File: library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java [hunk 2]
```diff
@@ -56,7 +58,13 @@ public MoreActionDialog setChannelViewModel(ChannelViewModel viewModel) {
 
 
     public MoreActionDialog setMessage(Message message) {
-        this.message = message;
+        // Check Thread parent Message
+        if (viewModel.isThread() && TextUtils.isEmpty(message.getParentId())){
+            this.message = message.copy();
+            this.message.setId(viewModel.getThreadParentMessage().getValue().getId());
```
Comment (tbarbugli) [inline library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: are you sure you need to do this as well? looks very weird that you need to overwrite the message id with the one from the viewmodel

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: Yeah, We **need** this. when switching from main chat to Thread, we had initialized threadparent message's id to empty string.(since some reason as you know)

Comment (tbarbugli) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: what about we stop touch message.id completely? beside the sending part, the ID is something that should come from API or offline storage.

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: I had to handle it for switching between main channel messages and  Thread messages on only one message list recyclerview.
Got it, Let me think about it.

Comment (elevenetc) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: Agree about touching id. And it seems the whole issue is because of cloning entities. Cloning should be a severe exception, because it introduces synchronisation issues. And cloning must be constantly supported.

Comment (elevenetc) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: Removed cloning message and surprisingly everything works. @adrian09h could you briefly test the app? Maybe I missed something. If everything is ok will merge it.

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/Dialog/MoreActionDialog.java]: Will check right now.

**Comment by adrian09h** [comment]
@elevenetc , Thanks for your touching this issue.
But I have found the old issue from your new update.
I have done it like your way first of all(not cloning), but in this case while swap message list, the swap behavior looked weird(Tommaso's report) since two message list(main messages and thread messages) have a spacial one massage has same id that is thread parent message!
So I had to select the currently way about cloning of `threadParentmessage` and reset the message id by empty string.

- My last code behavior


- Your new update or my old way


Its makes really headache!

**Comment by elevenetc** [comment]
Fade in/fade out animation with a thread parent message requires of writing custom `ItemAnimator`. And `ItemAnimator` behaviour is quite complicated, default basic implementation takes almost 1000 lines of code to just animate shifted items with fade in/fade out transitions. That's just reality of Android animation framework. Checked also Telegram and they seems just disabled completely message items animation.

So I would prefer to fix 2 bugs, remove mess with cloning instances and have stable animation, but less fancy. And create new animation improvement issue which we can implement separately.

**Comment by adrian09h** [comment]
@elevenetc , merging is blocked.
