### PR TITLE
Fix/watch channel

### LINKED ISSUE #1048: Failed message looks like it's sent
Failed message looks like this:

image

Error is:
"Can't find channel with id livestream:sandbox2"

### PR DESCRIPTION
**Pull request by JcMinarro**
### Description
Fix race-condition when a channel is watched but the socket connection is not online yet
Fix #1048

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Changelog updated with client-facing changes
- ~[ ] New code is covered by unit tests~
- ~[ ] Comparison screenshots added for visual changes~
- [x] Reviewers added

### CODE REVIEW

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt [hunk 1]
```diff
@@ -598,6 +598,11 @@ internal class ChatDomainImpl internal constructor(
         // 0 ensure load is complete
         initJob.join()
 
+        activeChannelMapImpl
+            .values
+            .filter { it.errorWatching }
+            .forEach { it.watch() }
```
Comment (zsmb13) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt:604]: This might be worth a comment similar to the other ones in this method

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt [hunk 2]
```diff
@@ -651,13 +656,12 @@ internal class ChatDomainImpl internal constructor(
...
 
         // 4 recover events
-        if (isOnline()) {
+        if (recoveryNeeded && isOnline()) {
             replayEventsForActiveChannels()
         }
     }
 
     private suspend fun retryFailedEntities() {
-        delay(1000)
```
Comment (zsmb13) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt:660]: Do we know why this was here in the first place?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt [hunk 3]
```diff
@@ -431,15 +431,12 @@ internal class EventHandlerImpl(
...
-                    val recovered = domainImpl.isInitialized()
-
                     domainImpl.setOnline()
                     domainImpl.setInitialized()
-                    if (recovered && domainImpl.recoveryEnabled) {
-                        domainImpl.connectionRecovered(true)
-                    } else {
-                        domainImpl.connectionRecovered(false)
-                    }
+                    domainImpl.connectionRecovered(domainImpl.recoveryEnabled)
```
Comment (zsmb13) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:436]: While we're here, looks like `recoveryEnabled` could be a `val`, because we never update it, we just set it at the creation of `ChatDomainImpl`.  (Also, `ChatDomainImpl` has an unused internal ctor?)

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt (hunk 1 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt:604]: :+1:

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt (hunk 3 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:436]: :+1:

**Review by zsmb13 — APPROVED** [review]

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt [hunk 4]
```diff
@@ -431,15 +431,12 @@ internal class EventHandlerImpl(
...
+                }
+                is HealthEvent -> {
+                    domainImpl.connectionRecovered(false)
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:439]: Doesn't this cause you to trigger connection recovered every 30 seconds?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt (hunk 3 above)
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:436]: the new code here doesn't differentiate between first connect and recovery flow

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt [hunk 5]
```diff
@@ -365,6 +365,7 @@ internal class ChannelControllerImpl(
             return
         }
         runChannelQuery(QueryChannelPaginationRequest(limit))
+        errorWatching = recoveryNeeded
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:368]: what's the difference between these 2 variables?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt [hunk 6]
```diff
@@ -598,7 +598,13 @@ internal class ChatDomainImpl internal constructor(
         // 0 ensure load is complete
         initJob.join()
 
-        // 1 update the results for queries that are actively being shown right now
+        // 1 Watch all channels that failed, it is needed for channels that are created locally, in other case it won't be created on the server
+        activeChannelMapImpl
+            .values
+            .filter { it.errorWatching }
+            .forEach { it.watch() }
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt:605]: can be optimized by only calling watch for channels that we didn't receive after doing the query channels

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt (hunk 3 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:436]: If it is first connect, there wasn't any pending channel, neither anyy calls to be done on the server

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt (hunk 4 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/EventHandlerImpl.kt:439]: Only for calls that were failing

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 5 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:368]: Watch is only the first time. When you load more messages (older or newer), if they fails, we don't need to watch it again

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt (hunk 6 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt:605]: This list is going to be ~0 almost always
