### PR TITLE
[3089] Fix default events handler

### LINKED ISSUE #3089: Channel disappears when some other member is removed
**Describe the bug**

The `member.removed` and `notificaiton.removed_from_channel` events are handled incorrectly in `CustomChatEventHandler` in our sample app. They should only trigger the removal of a channel if the current user was removed from it.

**To Reproduce**
1. User1: Launch UI components sample app and create a named channel with User2 and User3
2. User2: Observe that the channel has appeared
3. User1: Remove irrelevant User3 from the channel
4. User2: the channel disappears

**Expected behavior**
User2 still sees the channel

### PR DESCRIPTION
**Pull request by bychkovdmitry**
### 🎯 Goal

Closes #3089

Don't remove the channel from the UI if a member removal event arrives and the removed member is no the current user.

### 🧪 Testing

1. User1: Launch UI components sample app and create a named channel with users User2 and User3
2. User2: Observe that the channel has appeared
3. User1: Remove irrelevant User3 from the channel

Actual result:
User2: the channel disappears from the channel list even though user2 is still a member of the channel

Expected result:
User2 observes that the number of sections in the channel's avatar is reduced and the channel remains in the list

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [x] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

### CODE REVIEW

File: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt [hunk 1]
```diff
@@ -82,6 +83,21 @@ class CustomChatEventHandler(private val channels: StateFlow<List<Channel>>) : B
         }
     }
 
+    private fun handleMemberRemoval(
```
Comment (leandroBorgesFerreira) [inline stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt:86]: This class is only used in the Sample app. Shouldn't we add this same logic in `DefaultChatEventHandler`

**Review by leandroBorgesFerreira — COMMENTED** [review]
One comment

**Review by adasiewiczr — APPROVED** [review]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [ ] ~Compose sample runs & works~
- [ ] ~UI Changes correct (before & after images)~
- [x] Bugs validated (bugfixes)
- [ ] ~New feature tested and works~
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs
