### PR TITLE
[3369] video thumbnails UI components gallery

### LINKED ISSUE #3369: Previews of videos are not visible in messageList on Android, but on iOS yes
**Describe the bug**
When you send a video via Stream on a channel, you don't have any preview on Android, but on iOS yes. (see screenshots below)

**SDK version**
- 5.0.2

**To Reproduce**
1. Click on the attachment button on the input view
2. Choose a video
3. Send it
4. Check on both Android and iOS and see the difference

**Expected behavior**
It would be glad if we could also have a preview of the video on the message list. It would avoid both apps to have different designs and also different behaviors. It is also more convenient to have the preview rather than the filename so we can figure out what the video is.

**Device:**
 - Vendor and model: Pixel 3
 - Android version: Android 12

**Screenshots**
| iOS | Android |
|:-:|---|
| file | Screenshot_20220422_103554 |

### PR DESCRIPTION
**Pull request by MarinTolic**
### 🎯 Goal

closes #3369

### 🛠 Implementation details

Implemented the ability to display video items in the previously used image attachment gallery.

#### Gallery Offline

| Before | After |
| --- | --- |
| Screenshot_1666093619 | Screenshot_1666093883 |

#### Gallery Online

| Before | After |
| --- | --- |
| Screenshot_1666093600  | Screenshot_1666093930 |

#### Video Reproduction

| Before | After |
| --- | --- |
| Screenshot_1666094024 | Screenshot_1666093960 |

#### Functionality Test

1. Upload or find a video, preferably more than one
2. Open it/ them in the gallery
3. Play videos, page through and share them to check that all functionalities work as expected

#### 

#### Customizability Test

Patch A:

1. Apply the patch below
5. Open a video in the gallery and expand the media overview (bottom sheet)
6. Confirm that the customized parameters have been applied.

<details>

<summary>Customizability Patch</summary>

```
Index: stream-chat-android-ui-components/src/main/res/values/styles.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-ui-components/src/main/res/values/styles.xml b/stream-chat-android-ui-components/src/main/res/values/styles.xml
--- a/stream-chat-android-ui-components/src/main/res/values/styles.xml	(revision e3b1137a180305fb4b785e393283a80a315ef9c9)
+++ b/stream-chat-android-ui-components/src/main/res/values/styles.xml	(date 1666095213068)
@@ -846,27 +846,29 @@
 
     <style name="StreamUi.AttachmentGallery.VideoAttachments">
         <item name="streamUiAttachmentGalleryViewMediaPlayVideoButtonIcon">@drawable/stream_ui_ic_play</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconElevation">3dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingTop">2dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingBottom">2dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingStart">3dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingEnd">2dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconCornerRadius">24dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconBackgroundColor">@color/stream_ui_literal_white</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconElevation">0dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingTop">10dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingBottom">10dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingStart">10dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingEnd">10dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconCornerRadius">3dp</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconBackgroundColor">@color/stream_ui_black_50</item>
         <item name="streamUiAttachmentGalleryViewMediaPlayIconWidth">45dp</item>
         <item name="streamUiAttachmentGalleryViewMediaPlayIconHeight">45dp</item>
-        <item name="streamUiAttachmentGalleryViewMediaImagePlaceholder">@drawable/stream_ui_picture_placeholder</item>
+        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconTint">@color/stream_ui_literal_white</item>
+        <item name="streamUiAttachmentGalleryViewMediaImagePlaceholder">@drawable/stream_ic_notification</item>
     </style>
 
     <style name="StreamUi.MediaAttachmentGridView">
-        <item name="streamUiMediaAttachmentGridViewPlayVideoButtonIcon">@drawable/stream_ui_ic_play</item>
+        <item name="streamUiMediaAttachmentGridViewPlayVideoButtonIcon">@drawable/stream_ui_ic_filled_right_arrow</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconElevation">3dp</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingTop">2dp</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingBottom">2dp</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingStart">3dp</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingEnd">2dp</item>
         <item name="streamUiMediaAttachmentGridViewPlayVideoIconCornerRadius">24dp</item>
-        <item name="streamUiMediaAttachmentGridViewPlayVideoIconBackgroundColor">@color/stream_ui_literal_white</item>
+        <item name="streamUiMediaAttachmentGridViewPlayVideoIconBackgroundColor">@color/stream_ui_black_50</item>
+        <item name="streamUiMediaAttachmentGridViewPlayVideoIconTint">@color/stream_ui_accent_blue</item>
         <item name="streamUiMediaAttachmentGridViewImagePlaceholder">@drawable/stream_ui_picture_placeholder</item>
     </style>
 
```

</details>

Test B: 

1. Apply the patch below
2. Enter a channel with a video or send one to a channel
3. Reply to the video
4. Check that the video thumbnail isn't being displayed in the original message, reply to the message or the gallery

<details>

<summary>Patch that disables thumbnails</summary>

```
Index: stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
--- a/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt	(revision 9f3ecede5170c18057bc3e250c133765c34ed8e7)
+++ b/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt	(date 1666096933672)
@@ -19,6 +19,7 @@
 import android.app.Application
 import io.getstream.chat.android.client.utils.internal.toggle.ToggleService
 import io.getstream.chat.android.core.internal.InternalStreamChatApi
+import io.getstream.chat.android.ui.ChatUI
 import io.getstream.chat.ui.sample.data.user.SampleUser
 import io.getstream.chat.ui.sample.data.user.UserRepository
 
@@ -33,6 +34,7 @@
         initializeToggleService()
         chatInitializer.init(getApiKey())
         instance = this
+        ChatUI.videoThumbnailsEnabled = false
         DebugMetricsHelper.init()
         ApplicationConfigurator.configureApp(this)
     }
```

</details>

#### General
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [x] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

gif

### CODE REVIEW

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt [hunk 1]
```diff
@@ -0,0 +1,263 @@
...
+
+    /**
+     * If the video has been prepared and the video player
+     * is ready for playback.
+     *
+     * VideoView does not expose state so we use these to track
+     * state externally.
+     */
+    private var playbackPrepared = false
+        set(value) {
```
Comment (MarinTolic) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt:63]: `VideoView` does not expose it's internal state properly so as a consequence we have these overly complex external state trackers.

I don't like them and I don't think they are bulletproof. I'll add a discussion card to see if we might want to revisit our decision to not depend on media players such as ExoPlayer.

The [info listener](https://developer.android.com/reference/android/media/MediaPlayer.OnInfoListener) unfortunately did not yield any concrete results. It would fire the first time that the video would start, but then ignore any subsequent playback actions. Any sort of state tracking with this View seems to have been an after thought.

File: stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery_options_view.xml [hunk 2]
```diff
@@ -49,7 +49,7 @@
             />
 
         <TextView
-            android:id="@+id/saveImage"
+            android:id="@+id/saveMedia"
             style="@style/StreamUiMessageOptionItem"
             android:text="@string/stream_ui_attachment_gallery_save_image"
```
Comment (bychkovdmitry) [inline stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery_options_view.xml:54]: Should this be "Save media", or "Save image" / "Save video" depending on the selected page?

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/overview/MediaAttachmentGridView.kt [hunk 3]
```diff
@@ -80,9 +85,12 @@ public class MediaAttachmentGridView : FrameLayout {
     }
 
     private fun init(context: Context, attrs: AttributeSet?) {
```
Comment (bychkovdmitry) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/overview/MediaAttachmentGridView.kt:87]: I think the code above is incorrect. The Context passed to the `init` method is not wrapped. Could you check the scenario below? 

```
<style name="StreamUiTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
     ...
     <item name="streamUiMediaAttachmentGridViewStyle">@style/StreamUi.MediaAttachmentGridView</item>
</style>     
     
     
<style name="StreamUi.MyCustomMediaAttachmentGridView">
        <!-- This guy is different -->
        <item name="streamUiMediaAttachmentGridViewPlayVideoButtonIcon">@drawable/stream_ui_ic_umnute</item>

        <item name="streamUiMediaAttachmentGridViewPlayVideoIconElevation">3dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingTop">2dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingBottom">2dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingStart">3dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconPaddingEnd">2dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconCornerRadius">2dp</item>
        <item name="streamUiMediaAttachmentGridViewPlayVideoIconBackgroundColor">@color/stream_ui_literal_white</item>
        <item name="streamUiMediaAttachmentGridViewImagePlaceholder">@drawable/stream_ui_picture_placeholder</item>
    </style>    
```

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt [hunk 4]
```diff
@@ -0,0 +1,263 @@
...
+
+    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
+        super.onViewCreated(view, savedInstanceState)
+        setupVideoThumbnail()
+        setupPlayButton()
+        loadVideo()
+    }
+
+    private fun setupVideoThumbnail() {
+        if (ChatUI.videoThumbnailsEnabled) {
```
Comment (bychkovdmitry) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt:142]: Not an issue, but feels a bit low level for `ChatUI`. Let's discuss later. Could be for exmaple:
```
ChatUI.meesageListConfig.videoThumbnailsEnabled
```

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt [hunk 5]
```diff
@@ -0,0 +1,263 @@
...
+     *
+     * Fetching the style depends on [Context] so use this property
+     * only after it has been obtained during or after [onAttach].
+     */
+    private val style by lazy {
+        AttachmentGalleryViewMediaStyle(
+            context = requireContext(),
+            attrs = null
+        )
+    }
```
Comment (bychkovdmitry) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/internal/AttachmentGalleryVideoPageFragment.kt:53]: Same here, should work only if Context is wrapped `requireContext().createStreamThemeWrapper()`.

```
    <style name="StreamUiTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
       ...
        <item name="streamUiAttachmentGalleryVideoAttachmentsStyle">@style/StreamUi.AttachmentGallery.MyCustomVideoAttachments</item>
    </style>

    <style name="StreamUi.AttachmentGallery.MyCustomVideoAttachments">
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoButtonIcon">@drawable/stream_ui_ic_audio</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconElevation">3dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingTop">2dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingBottom">2dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingStart">3dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconPaddingEnd">2dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconCornerRadius">24dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayVideoIconBackgroundColor">@color/stream_ui_literal_white</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayIconWidth">45dp</item>
        <item name="streamUiAttachmentGalleryViewMediaPlayIconHeight">45dp</item>
        <item name="streamUiAttachmentGalleryViewMediaImagePlaceholder">@drawable/stream_ui_picture_placeholder</item>
    </style>
```

**Review by bychkovdmitry — CHANGES_REQUESTED** [review]

**Review by bychkovdmitry — APPROVED** [review]
LGTM

File: stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery_options_view.xml (hunk 2 above)
Comment (MarinTolic) [reply stream-chat-android-ui-components/src/main/res/layout/stream_ui_attachment_gallery_options_view.xml]: fixed
