### PR TITLE
Fix refreshing channels list when syncing the channel

### LINKED ISSUE #3257: Improve handling events inside QueryChannelsLogic

### PR DESCRIPTION
**Pull request by adasiewiczr**
closes #3257 

### 🎯 Goal

Fix refreshing channels list when syncing the channel.

### 🛠 Implementation details

`QueryChannelsLogic` shouldn't try to refresh the channel if it's not present in the memory yet as it might be not populated with data.

### 🎨 UI Changes
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/17440581/167579906-721614e1-98d8-4f11-8ca6-480c1c4108f3.mp4" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/17440581/167579868-5156358a-7fb5-47a2-a9b4-b9aabde9a537.mp4" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

### 🧪 Testing
1. Turn on airplane mode and send a message in the channel
2. Kill the app
3. Open the app and stay on the channels list
4. Turn off airplane mode
5. Observe channels list

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] Bugs validated (bugfixes)
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### CODE REVIEW

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt [hunk 1]
```diff
@@ -287,11 +288,21 @@ internal class QueryChannelsLogic(
...
+                    channelId = channelId,
+                )
+            }
+            .associate { (channelType, channelId) ->
+                val cid = (channelType to channelId).toCid()
+                cid to stateRegistry.channel(
+                    channelType = channelType,
+                    channelId = channelId,
+                ).toChannel()
             }
```
Comment (JcMinarro) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt:306]: We are not keeping the result anywhere, is it right?

Comment (adasiewiczr) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt:306]: good catch! Thank you!

**Review by JcMinarro — APPROVED** [review]
LGTM
