### PR TITLE
fix Bug: NullPointerException when channelState.getLastMessage() is n…

### LINKED ISSUE #57: Bug: NullPointerException when channelState.getLastMessage() is null
The [tutorial](https://getstream.io/tutorials/android-chat/#kotlin) provided in Stream's documentation instructs the reader to copy the sample code from the tutorial as-is. 

When using the sample credentials provided, the `lastMessage` for the `ChannelState` object that is returned is null, and causes the line `channelState.getLastMessage().setStatus(MessageStatus.RECEIVED);` to throw an NPE. 

Stacktrace:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.getstream.sdk.chat.rest.Message.setStatus(com.getstream.sdk.chat.enums.MessageStatus)' on a null object reference
>         at com.getstream.sdk.chat.rest.core.Client$3$1.onResponse(Client.java:470)
>         at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Dependency: `com.github.getstream:stream-chat-android:1.9.1'

Steps to Reproduce:
1. Copy setup from tutorial
2. Copy ChannelList section from tutorial
3. Run the application
4. Observe NPE

### PR DESCRIPTION
**Pull request by adrian09h**
…ull closed #57

# Submit a pull request

Fix #57

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java [hunk 1]
```diff
@@ -467,7 +467,8 @@ public void onSuccess(User user) {
                     public void onResponse(Call<QueryChannelsResponse> call, Response<QueryChannelsResponse> response) {
 
                         for (ChannelState channelState : response.body().getChannelStates()) {
-                            channelState.getLastMessage().setStatus(MessageStatus.RECEIVED);
+                            if (channelState.getLastMessage() != null)
+                                channelState.getLastMessage().setStatus(MessageStatus.RECEIVED);
```
Comment (tbarbugli) [inline library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java]: shouldn't we do this when we unmarshal JSON responses with messages? this approach sounds pretty fragile / prone to bugs (ie. we don't do this on `channel.query`)

Comment (tschellenbach) [reply library/src/main/java/com/getstream/sdk/chat/rest/core/Client.java]: what's the reason for setting the message status here?
