### PR TITLE
CAS-81 Fix/Crash_app_on_add_attachment_api_29

### LINKED ISSUE #403: CAS-81: App crashes on attaching photo or video
In the chat detail, clicking on the **"Upload a photo or video"** option when trying to attach a file to a conversation throws the error. I'm using version 3.6.1, my target sdk version is 29. I've noticed the error on devices running Android 10 
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask 
    java.lang.IllegalArgumentException: Invalid column resolution
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.getstream.sdk.chat.utils.Utils.getMediaAttachments(Utils.java:226)
        at com.getstream.sdk.chat.utils.MessageInputController.getAttachmentsFromLocal(MessageInputController.java:183)
        at com.getstream.sdk.chat.utils.MessageInputController.configSelectAttachView(MessageInputController.java:164)
        at com.getstream.sdk.chat.utils.MessageInputController.lambda$onClickOpenSelectView$5$MessageInputController(MessageInputController.java:310)
        at com.getstream.sdk.chat.utils.-$$Lambda$MessageInputController$v0Qk8BORwmsngO6TsPKo64HGs2E.run(Unknown Source:4)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

### PR DESCRIPTION
**Pull request by andriizhumela**
Fixes #403

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/utils/Utils.java [hunk 1]
```diff
@@ -208,7 +208,6 @@ public static int pxToDp(int px) {
                 MediaStore.Files.FileColumns.MEDIA_TYPE,
                 MediaStore.Files.FileColumns.MIME_TYPE,
                 MediaStore.Files.FileColumns.TITLE,
-                MediaStore.Video.Media.RESOLUTION,
```
Comment (andriizhumela) [inline library/src/main/java/com/getstream/sdk/chat/utils/Utils.java]: On 29 ver. we have no access to MediaStore.Video.Media fields

File: library/src/main/java/com/getstream/sdk/chat/utils/Utils.java [hunk 2]
```diff
@@ -230,7 +229,11 @@ public static int pxToDp(int px) {
                 MediaStore.Files.FileColumns.DATE_ADDED + " DESC" // QuerySort order.
         );
 
-        int image_column_index = imagecursor.getColumnIndex(MediaStore.Files.FileColumns._ID);
+        if (imagecursor == null) {
+            StreamChat.getLogger().logE(Utils.class, "ContentResolver query return null");
+            return null;
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/utils/Utils.java]: Empty list should be returned, otherwise there will be another crash.
