### PR TITLE
[AND-552] Fix UninitializedPropertyAccessException in AttachmentsPickerSystemFragment

### LINKED ISSUE #5760: kotlin.UninitializedPropertyAccessException in AttachmentsPickerSystemFragment
**Crash Report**
```
kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
	at io.getstream.chat.android.ui.feature.messages.composer.attachment.picker.factory.system.internal.AttachmentsPickerSystemFragment.setupViews(AttachmentsPickerSystemFragment.kt:105)
	at io.getstream.chat.android.ui.feature.messages.composer.attachment.picker.factory.system.internal.AttachmentsPickerSystemFragment.onViewCreated(AttachmentsPickerSystemFragment.kt:94)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3230)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3153)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3237)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at com.base.BaseActivity.onStart(BaseActivity.kt:118)
	at com.unified_chat.presentation.view.ChannelActivity.onStart(ChannelActivity.kt:275)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
	at android.app.Activity.performStart(Activity.java:8628)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

Fragment is initialized using the following code in Fragment:
```
fun newInstance(
            style: AttachmentsPickerDialogStyle,
            attachmentsPickerTabListener: AttachmentsPickerTabListener,
            config: AttachmentsPickerSystemConfig,
        ): Fragment = AttachmentsPickerSystemFragment().apply {
            this.style = style
            this.attachmentsPickerTabListener = attachmentsPickerTabListener
            this.config = config
}
```
Above code will work for default normal situations, but wont work situations where system kills activity and re-create.

When an activity & fragment is recreated, system will never call the above code. It will initialize the fragment with default constructor, missing all the late-init variables not initialized or set.

Either pass the data using fragment setArguments or need to make the variable nullable or check variable is initialized or not, then handle the code accordingly.

**SDK version**
- 6.6.0 (Crash can happen even in latest version too)

**To Reproduce**
1. In phone Developer options, enable "Don't keep activities" `(Important part, to test low memory situations)`
2. Open any getstream sample chat code app, which has composer with attachment option enabled.
3. Click on attachment button from composer.
4. Attachment bottomSheet will be shown. Keep as it is, don't close.
5. Minimize the app, system will destroy the activity.
6. Open the app from history, system will recreate the activity and fragments.
7. App will crash

**Expected behavior**
1. Either use fragment.setArguments to pass data (Recommended & right way)
2. or Make all the lateinit variable nullable and handle null situations
3. or Keep lateinit, but check variable is initialized or not before using it. `::config.isInitialized`

### PR DESCRIPTION
**Pull request by andremion**
### 🎯 Goal

Fix #5760 

### 🛠 Implementation details

- `AttachmentsPickerSystemFragment`:
    - Changed `config` property to be passed as fragment arguments, making it state-restorable.
    - Removed the fragment in `onViewCreated` if `style` is not initialized or `savedInstanceState` is not null, preventing crashes when the fragment is recreated without necessary data.
- `AttachmentsPickerDialogFragment`:
    - Added a check in `onDismiss` to ensure `style` is initialized before accessing its properties.

### 🎨 UI Changes

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/20440df5-e074-4b5a-93c7-ab0758b8678b" controls="controls" muted="muted" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/1fffcdd1-07f3-47f7-b2b6-565d4ae81e8e" controls="controls" muted="muted" />
</td>
</tr>
</tbody>
</table>

### 🧪 Testing

- Comment out these lines in the HostActivity of the `ui-components-sample`

```kotlin
// if (savedInstanceState != null && lastNonConfigurationInstance == null) {
//     // the application process was killed by the OS
//     startActivity(packageManager.getLaunchIntentForPackage(packageName))
//     finishAffinity()
// }
```
- Enable system attachments picker in `fragment_chat.xml` layout

```xml
app:streamUiMessageComposerAttachmentsPickerSystemPickerEnabled="true"
```

- In phone Developer options, enable `Don't keep activities`.
- Open `ui-components` sample app, click on a channel and click to add a attachment.
- Minimize the app.
- Open the app from history.

### 🎉 GIF

gif

### CODE REVIEW

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/factory/system/internal/AttachmentsPickerSystemFragment.kt [hunk 1]
```diff
@@ -85,7 +85,13 @@ internal class AttachmentsPickerSystemFragment : Fragment() {
 
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
         super.onViewCreated(view, savedInstanceState)
-        setupViews()
+        if (savedInstanceState == null && ::style.isInitialized) {
+            setupViews()
+        } else {
+            parentFragmentManager.beginTransaction()
```
Comment (VelikovPetar) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/factory/system/internal/AttachmentsPickerSystemFragment.kt:91]: Just for my understanding: This will basically result in the dialog being closed for orientation changes as well? (but from what I can see, we have to it this way, because of how the `Style` is passed to the Dialog)

Comment (andremion) [reply stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/picker/factory/system/internal/AttachmentsPickerSystemFragment.kt:91]: Exactly. There are many other dialog fragments that behave the same way. The entire SDK is built with this premise.
