### PR TITLE
[4297] V5 Make attachment equality comparisons based on shortened links

### LINKED ISSUE #4297: AttachmentGalery delete not working after attachments are sent
**Describe the bug**
After a list of media attachemtns is sent, deleting a single attachment doesn't work untill refreshing the list. It seems that localy the `imageUrl` of the `Attachemnt` does not get properly updated after upload has finished.

**To Reproduce**
1. Send a list of media attachments to channel
2. Open an attachemtn and select delete from menu
3. Attachment doesnt delete

**Expected behavior**
The attachment should be deleted after clicking delete inside `AttachmentGallery`

### PR DESCRIPTION
**Pull request by MarinTolic**
### 🎯 Goal

Closes #4297 

### 🛠 Implementation details

Instead of comparing the full attachment link which might differ depending on when it was loaded, fallback to comparing a shortened URL

This PR technically touches upon the compose SDK as well since they share the new `MessageListController` , however the Compose SDK uses internal logic inside `MediaGalleryPreviewViewModel.deleteCurrentMediaAttachment()` so it will not be affected in the compose sample app.

### 🧪 Testing

**Note**: It is important to always test freshly uploaded attachments, they must always be the latest message without navigating away from the message list in any way.

#### Previous behavior

1. Checkout `develop`
2. Launch the UI Components sample app
3. Send a message with multiple image and/or video attachments
4. Open an attachment in the gallery.
5. Delete an attachment via the gallery

**Result:** The attachment was not deleted

#### Deleting attachments

1. Checkout `develop`
2. Launch the UI Components sample app
3. Send a message with multiple image and/or video attachments
4. Open an attachment in the gallery.
5. Delete an attachment via the gallery

**Result:** The attachment is deleted

#### Deleting all attachments

1. Checkout `develop`
2. Launch the UI Components sample app
3. Send a message with multiple image and/or video attachments
4. Open an attachment in the gallery.
5. Delete all attachments inside the message

You should repeat this test in the following fashion

1. With a blank message (Result: Message is deleted when the last remaining attachment has been deleted)
2. With a message containing a text (Result: All attachments are removed, message remains)
3. With a message containing a hyperlink (Result: All attachments are removed, message remains and is transformed into a link attachment)

#### General
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes (the changelog has been updated in the `v5` version of this PR: https://github.com/GetStream/stream-chat-android/pull/4349)
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

gif

### CODE REVIEW

File: stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt [hunk 1]
```diff
@@ -638,22 +638,43 @@ public class MessageListViewModel(
...
-                            if (attachmentToBeDeleted.assetUrl != null) {
-                                attachment.assetUrl == attachmentToBeDeleted.assetUrl
-                            } else {
-                                attachment.imageUrl == attachmentToBeDeleted.imageUrl
+                            val imageUrl = attachmentToBeDeleted.imageUrl
+                            val assetUrl = attachmentToBeDeleted.assetUrl
+
+                            when {
+                                assetUrl != null -> {
+                                    attachment.assetUrl?.substringBefore("?") ==
```
Comment (MarinTolic) [inline stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt:648]: substringBefore() will return the original string if it cannot satisfy this condition.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/substring-before.html

File: stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt [hunk 2]
```diff
@@ -638,22 +638,43 @@ public class MessageListViewModel(
...
                             }
                         }
 
-                        chatClient.updateMessage(message).enqueue(
-                            onError = { chatError ->
-                                logger.e {
-                                    "Could not edit message to remove its attachments: ${chatError.message}. " +
-                                        "Cause: ${chatError.cause?.message}"
+                        if (message.text.isBlank() && message.attachments.isEmpty()) {
+                            chatClient.deleteMessage(messageId = event.messageId).enqueue(
```
Comment (MarinTolic) [inline stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt:660]: Because we previously did not do this, we would leave behind an empty message if the last attachment was deleted.

**Review by TGazica — CHANGES_REQUESTED** [review]
Same as in the V6 pr: https://github.com/GetStream/stream-chat-android/pull/4348#pullrequestreview-1175319581

**Review by TGazica — APPROVED** [review]
Looks good, bug to be fixed in other pr
