### PR TITLE
Feature/Fix message readcount

### LINKED ISSUE #168: Read count is inconsistent
### Read count for own message

image

### Read count for other user

image

Somehow the unread count for own messages is different (not sure which one is wrong)

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request

close #168

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java [hunk 1]
```diff
@@ -82,7 +81,7 @@ private void init() {
         }
         // Count Text
         TextView textView = new TextView(getContext());
-        textView.setText(String.valueOf(reads.size()));
+        textView.setText(String.valueOf(reads.size() - 1));
```
Comment (tbarbugli) [inline library/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java]: - does `read` always contain current user? if not then this count will be wrong?
- what about empty read state? this will set the text to -1

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java]: > does read always contain current user? if not then this count will be wrong?
`read` doesn't contain always current user.
Please see this line
https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/utils/MessageListItemLiveData.java#L89

```java
        ...
        // this wil become slow with many users and many messages
        for (Map.Entry<String, ChannelUserRead> entry : readsByUser.entrySet()) {
            // we don't show read state for the current user
            if (entry.getValue().getUser().getId().equals(currentUser.getId())) {
                continue;
            }
        ...
```

> what about empty read state? this will set the text to -1
There won't be this case. ;)
Please see this  line
https://github.com/GetStream/stream-chat-android/blob/master/library/src/main/java/com/getstream/sdk/chat/view/ReadStateView.java#L49

```java
if (!style.isShowReadState()
    || reads == null
    || reads.isEmpty()) return;
```

File: library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java [hunk 2]
```diff
@@ -147,7 +147,7 @@ public void bind(Context context, ChannelState channelState, int position) {
         // read indicators
         read_state.setReads(lastMessageReads, true, style);
 
-        if (channelState.readLastMessage())
+        if (channelState.readLastMessage() || lastMessage.getUserId().equals(channel.getClient().getUserId()))
```
Comment (tbarbugli) [inline library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java]: missing null check here?

Comment (adrian09h) [reply library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java]: fixed

File: library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java [hunk 3]
```diff
@@ -979,9 +979,9 @@ public void sendMessage(Message message, MessageCallback callback) {
         }
 
         // TODO: I'm reading this code and i don't get what it does, needs some clarification (Thierry)
-        if (client().isConnected()) {
-            channel.getChannelState().setReadDateOfChannelLastMessage(client().getUser(), message.getCreatedAt());
-        }
+//        if (client().isConnected()) {
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java]: Just delete if it's not really needed. Or leave a comment about why it's needed to be here commented.
