### PR TITLE
[3150] Fix members count of Channels

### LINKED ISSUE #3150: Channel member counter only counts up to 30
ways to replicate:
1) add more than 30 users into a channel
2) open a channel to see the member counter

expected: correct number of member count
actual: 30 members

### PR DESCRIPTION
**Pull request by amitkma**
Closes #3150 

### 🎯 Goal
When a channel is opened, the member counts are derived from the `ChannelState::members` property which contains members up to `memberLimit` passed in `queryChannel` requests (default to 30). So it doesn't show the correct number of all members in that channel.

### 🛠 Implementation details

- Added `ChannelState::membersCount` property which is updated with `Channel::memberCount`.
- Added `membersCount` property in `MessageListHeaderViewModel`.

### 🧪 Testing

- Run the sample app, and add more than 30 members to a channel.
- Message list header should show the correct number of members and not 30.

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### CODE REVIEW

**Review by filbabic — APPROVED** [review]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] UI Changes correct (before & after images)
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt [hunk 1]
```diff
@@ -51,13 +51,16 @@ internal fun Channel.updateLastMessage(message: Message) {
...
-internal fun Channel.setMember(userId: String, member: Member?) {
+internal fun Channel.setMember(userId: String, member: Member?, isUpdate: Boolean = false) {
     if (member == null) {
         members.firstOrNull { it.user.id == userId }?.also { foundMember ->
             members = members - foundMember
+            memberCount -= 1
         }
     } else {
         members = members + member
+        if (!isUpdate)
```
Comment (filbabic) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt:62]: Can we just wrap this in {} just in case? it's much nicer that way!

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt [hunk 2]
```diff
@@ -51,13 +51,17 @@ internal fun Channel.updateLastMessage(message: Message) {
     }
 }
 
-internal fun Channel.setMember(userId: String, member: Member?) {
+internal fun Channel.setMember(userId: String, member: Member?, isUpdate: Boolean = false) {
```
Comment (adasiewiczr) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/internal/Channel.kt:54]: I would rather remove this default parameter and make it explicit everywhere. 
Can we change the method's name to match its behavior?
Can we also add KDoc to this method?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt [hunk 3]
```diff
@@ -333,6 +333,7 @@ internal class ChannelLogic(
         setWatcherCount(c.watcherCount)
 
         mutableState._read.value?.lastMessageSeenDate = c.lastMessageAt
+        mutableState._membersCount.value = c.memberCount
```
Comment (adasiewiczr) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt:336]: Shouldn't we also do the same in `updateOldMessagesFromChannel`? 🤔

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt [hunk 4]
```diff
@@ -770,6 +772,7 @@ internal class ChannelLogic(
                 deleteMember(event.user.id)
             }
             is MemberAddedEvent -> {
+                mutableState._membersCount.value += 1
```
Comment (adasiewiczr) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt:775]: What about `NotificationAddedToChannelEvent`?

**Review by adasiewiczr — COMMENTED** [review]
Left some comments. Let's make sure the count works correctly after adding/removing members

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt [hunk 5]
```diff
@@ -385,7 +385,7 @@ internal class EventHandlerImpl(
                 }
                 is MemberUpdatedEvent -> {
```
[the remark this answers is not in the document]
Comment (amitkma) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt:386]: We were not calling `setMember`  in `NotificationAddedToChannelEvent`. So not sure if we should increase the count as well?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt (hunk 3 above)
Comment (amitkma) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt:336]: Good catch.

**Review by adasiewiczr — APPROVED** [review]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] UI Changes correct (before & after images)
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs
