### PR TITLE
fix: CAS-358 fix channels being stuck in the unread state

### LINKED ISSUE #698: Latest message not updating
In the channel list, the latest message never updates in a same session. This is the latest 4.3.0-beta-6

out

### PR DESCRIPTION
**Pull request by carterhudson**
https://stream-io.atlassian.net/browse/CAS-358

### Description

Issues:
- Our logic for visually indicating as read in the channel list only renders as read if the last read date is newer than the last message date, but the API marks reads with the message's createdAt date. This makes the comparison EQUAL, especially from online query results.

- Additionally, if we got into the state where last read & last message dates are equal, we don't send markRead updates to the UI or the API because the logic indicates we only do that if the last read date is AFTER the last message date. So, we end up stuck in an unread state.

- We execute several concurrent data fetches for offline & online. The mark read usecase gets executed immediately when a message list view loads, even before the viewmodel has a chance to run a channel query for offline and online data. This means we optimistically update the UI, then send a message to the backend to mark a message as read, then execute an offline & online query. It's possible for these last read dates to differ / be old, especially since a MessageReadEvent will be received in the middle of these updates, triggering offline caching. The online job may also return outdated reads.

Changes:
- Since last lastRead == createdAt is expected in online responses, change the logic for rendering as read to >= instead of >.- Refactor updateReads to avoid pushing old read dates to the UI.
- Refactor markRead to check error states first and provide explicit logging.

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Changelog updated with client-facing changes
- [x] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [x] Reviewers added

Fixes #698

### CODE REVIEW

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt [hunk 1]
```diff
@@ -232,24 +232,37 @@ internal class ChannelControllerImpl(
...
-            }
+        if (messages.isEmpty()) {
+            logger.logI("No messages; nothing to mark read.")
+            return Result(false, null)
         }
-        return Result(false, null)
+
+        val last = messages.last()
+        val lastMessageDate = last.let { it.createdAt ?: it.createdLocallyAt }
+        val shouldNotUpdate =
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:249]: shouldMarkRead would be easier to read, the not X variable name is hard to read

Comment (carterhudson) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:249]: Would you prefer `!shouldUpdate` vs `shouldNotUpdate`?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt [hunk 2]
```diff
@@ -1017,20 +1044,39 @@ internal class ChannelControllerImpl(
...
-            _read.postValue(it)
-            println("updateReads for current user to ${it.lastRead} on channel $cid")
+        val previousUserIdToReadMap = _reads.value ?: mapOf()
+        val incomingUserIdToReadMap = reads.associateBy(ChannelUserRead::getUserId).toMutableMap()
+
+        /*
+        It's possible that the data coming back from the online channel query has a last read date that's before
+        what we've last pushed to the UI. We want to ignore this, as it will cause an unread state to show in the
+        channel list.
+         */
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:1056]: @carterhudson i don't get this, we don't show your own unread state...

Comment (tschellenbach) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:1056]: do we perhaps receive mark read events out of order? @tbarbugli is that possible?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt [hunk 3]
```diff
@@ -232,24 +232,37 @@ internal class ChannelControllerImpl(
...
-                return Result(true, null)
-            }
+        if (messages.isEmpty()) {
+            logger.logI("No messages; nothing to mark read.")
+            return Result(false, null)
         }
-        return Result(false, null)
+
+        val last = messages.last()
+        val lastMessageDate = last.let { it.createdAt ?: it.createdLocallyAt }
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:248]: @tbarbugli how does the backend API actually handle the mark read call? The usage of createdLocallyAt is a bit funky here

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt [hunk 4]
```diff
@@ -515,7 +533,10 @@ internal class ChannelControllerImpl(
                 Result(processedMessage, null)
             } else {
 
-                logger.logE("Failed to send message with id ${newMessage.id} and text ${newMessage.text}: ${result.error()}", result.error())
+                logger.logE(
+                    "Failed to send message with id ${newMessage.id} and text ${newMessage.text}: ${result.error()}",
+                    result.error()
+                )
```
Comment (tschellenbach) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:539]: @carterhudson which editor are you using and did you run `ktlint applyToIDEAProject`?

**Comment by tschellenbach** [comment]
1. I think we need to understand how the backend handles mark read API calls for messages that aren't created yet. IE the mark read using message.createdLocallyAt

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 4 above)
Comment (carterhudson) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:539]: I'm using Android Studio with the Project code style selected and a pre-commit hook that requires ktlintFormat to be run.

**Review by tschellenbach — DISMISSED** [review]
I think we still have edge cases with the createdLocallyAt, needs input from the backend team. 

It definitely seems better than before though, so lets go

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 2 above)
Comment (carterhudson) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:1056]: Hmm It's possible I misunderstood this. I give this another look.

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 3 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:248]: `createdLocallyAt` would be used only for offline messages that has not been sent to the server (because no connection, for example)

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 4 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:539]: Which command do you use to format the code into your pre-commit hook?
Using `./gradlew ktlintFormat` doesn't format those lines in the current project.

**Review by JcMinarro — CHANGES_REQUESTED** [review]
Look Good.
Could you update the Changelog?

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt (hunk 4 above)
Comment (carterhudson) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/controller/ChannelControllerImpl.kt:548]: Formatting those lines is a result of the Project codestyle I'm using. It's possible mine differs if we're not tracking it in version control.

**Review by JcMinarro — APPROVED** [review]
