### PR TITLE
Fix/Null check for Message

### LINKED ISSUE #270: Update channel without posting Message or posting as System message
The documentation for `updateChannel` says about the updateMessage; parameter "message allowing you to show a system message in the Channel that something changed", however, when I use this, it shows the message like it was the current user that made the update sent the message. For example, I rename a channel, and I want to show a `system` message not posted as the user making the update, can I achieve this (as the method here suggested)  without using hooks? Here's my example code to rename a channel and post a message that channel was renamed by the user.
```
channel.extraData[NAME] = newName
val message = Message().apply {
        text = "Group renamed to $newName"
        type = "system"
    }

val callback = object : ChannelCallback {
    override fun onSuccess(response: ChannelResponse?) {
       ...
    }
   override fun onError(errMsg: String?, errCode: Int) {
     ....
   }
}
streamClient.updateChannel(channel, message, callback)
```
If its not possible to do this, how do I update a channel without providing a value for the updateMessageparameter, because when I try provide that as null, updateChannel fails with the message Attempt to invoke virtual method 'java.util.HashMap com.getstream.sdk.chat.rest.Message.getExtraData()' on a null object reference.

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request

close #270

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/rest/adapter/MessageGsonAdapter.java [hunk 1]
```diff
@@ -24,7 +24,13 @@
 
     @Override
     public void write(JsonWriter writer, Message message) throws IOException {
+
         HashMap<String, Object> data = new HashMap<>();
+        TypeAdapter adapter = GsonConverter.Gson().getAdapter(HashMap.class);
+        if (message == null){
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/rest/adapter/MessageGsonAdapter.java]: Still weird and looks like a workaround. 
Lets leave a comment at least mentioning why there is this check.

Also googled briefly and apparently there was a bug before Gson 2.4: https://stackoverflow.com/a/55884142/798165
But we use the latest version. The link also I think should be mentioned in the comment.
