### PR TITLE
[3970] Fix watcher count

### LINKED ISSUE #3970: Watcher count not updated in MessageListHeader
**Describe the bug**
Watcher count not updated in `MessageListHeader`.

**To Reproduce**
1. User 1: Open a channel and check the number of online users in `MessageListHeader`.
2. User 2: Login and start watching the same channel.
3. User 1: Online user count is not updated in the header. 

**Expected behavior**
The online user count is updated for user 1.

We need to observe `watcherCount` as we do in XML:

**MessageListHeaderViewModel.kt**
```kotlin
public val channel: LiveData<Channel> =
    channelState.flatMapLatest { state ->
        combine(
            state.channelData,
            state.members,
            state.watcherCount
        ) { _, _, _ ->
            state.toChannel()
        }
}.asLiveData()
```

### PR DESCRIPTION
**Pull request by bychkovdmitry**
### 🎯 Goal

Closes #3970 

The number of online users is not updated in Compose.

### 🧪 Testing

1. User 1: Open Compose sample app
2. User 1: Navigate to the messages screen
3. User 1: Observe channel status (e.g. 31 Members, 3 Online)
4. User 2: From another device start watching this channel
5. User 1: Observe that the number of online members increased (31 Members, 4 Online)
6. User 2: Send the application to the background
7. User 1: Observe that the number of online members decreased (31 Members, 3 Online)

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

### CODE REVIEW

File: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt [hunk 1]
```diff
@@ -265,15 +265,16 @@ public class MessageListViewModel(
...
     /**
-     * Starts observing the current channel. We observe the 'messagesState', 'user' and 'endOfOlderMessages'
-     * states, as well as build the `newMessageState` using [getNewMessageState] and combine it
-     * into a [MessagesState] that holds all the information required for the screen.
+     * Starts observing messages of the current channel. We observe the 'messagesState', 'user' and
+     * 'endOfOlderMessages' states, as well as build the `newMessageState` using [getNewMessageState]
+     * and combine it into a [MessagesState] that holds all the information required for the screen.
      */
-    private fun observeChannel() {
+    private fun observeMessages() {
```
Comment (MarinTolic) [inline stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt:277]: Maybe we could call it `observeChannelState`.
It seems more technically correct.

File: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt [hunk 2]
```diff
@@ -331,18 +332,17 @@ public class MessageListViewModel(
...
-                                channelId = channel.id
-                            )
-                            setCurrentChannel(channel)
-                        }
                     }
             }
         }
     }
 
+    /**
```
Comment (MarinTolic) [inline stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt:340]: This Kdoc seems to be floating and connected to no actual code.

File: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt [hunk 3]
```diff
@@ -354,6 +354,30 @@ public class MessageListViewModel(
...
+     * Starts observing the current [Channel] created from [ChannelState]. It emits new data either when
```
Comment (MarinTolic) [inline stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt:358]:
```suggestion
     * Starts observing the current [Channel] created from [ChannelState]. It emits new data when either
```

File: stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt [hunk 4]
```diff
@@ -265,15 +265,16 @@ public class MessageListViewModel(
...
         observeTypingUsers()
+        observeMessages()
         observeChannel()
     }
 
     /**
-     * Starts observing the current channel. We observe the 'messagesState', 'user' and 'endOfOlderMessages'
-     * states, as well as build the `newMessageState` using [getNewMessageState] and combine it
-     * into a [MessagesState] that holds all the information required for the screen.
+     * Starts observing messages of the current channel. We observe the 'messagesState', 'user' and
```
Comment (MarinTolic) [inline stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt:273]:
```suggestion
     * Starts observing the messages in the current channel. We observe the 'messagesState', 'user' and
```

**Review by MarinTolic — CHANGES_REQUESTED** [review]
Requesting changes due to the floating kdoc.

File: CHANGELOG.md [hunk 5]
```diff
@@ -57,6 +57,7 @@
 
 ## stream-chat-android-compose
 ### 🐞 Fixed
+- Fixed the display of online member count in the message list header. [#4043](https://github.com/GetStream/stream-chat-android/pull/4043)
```
Comment (MarinTolic) [inline CHANGELOG.md:60]: Maybe we could be more descriptive here, possibly something like the following:

```suggestion
- Fixed the online member count indicator in the message list header. Previously it did not properly track members going offline. [#4043](https://github.com/GetStream/stream-chat-android/pull/4043)
```

**Review by MarinTolic — APPROVED** [review]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] Bugs validated (bugfixes)
- [x] New feature tested and works
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs
