### PR TITLE
Fix populating mentions when sending a message with attachments

### LINKED ISSUE #3797: @mentioning doesn't work on messages with an attachment
**Describe the bug**

When @mentioning another user on a message that also includes an attachment, the `mentionedUsers` list on the `Message` doesn't get populated.

This is reproducible in our own app on Stream v5.3.0, and in the current version of the `stream-chat-android-ui-components-sample`.

**SDK version**
- 5.3.0

**To Reproduce**
1. Go to any channel
2. Click the attachments button on the MessageInputView, and add an attachment (don't send yet)
3. @mention a user inside the MessageInputView
4. Click Send

**Expected behavior**

The message sends, and gets put into the message list with a Message including both an attachment and the mentioned user in the `mentionedUsers` list.

**Device:**
 - Vendor and model: Samsung Galaxy S21
 - Android version: 12

**Screenshots**

| UI including messages | Debugger: @mention + attachment | Debugger: @mention only |
| :--- | :--- | :--- |
| image | image | image |

### PR DESCRIPTION
**Pull request by adasiewiczr**
closes #3797 

### 🎯 Goal

Fix populating mentions when sending a message with attachments.

### 🛠 Implementation details
`Message:mentionedUserIds` were not properly stored in the DB. Before, we were only storing `Message::mentionedUsers` which is only populated after sending the message to the backend.
Added additional field to `MessageEntity` which separates `mentionedUserIds` (populated locally) and `mentionedUsers` (populated on server)

### 🧪 Testing
<details>
  <summary>Please apply this patch to reprdoce the issue.</summary>

```
Index: stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt b/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
--- a/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt	(revision ec47876a396b3377fec5ff3f6dad4776b215da6b)
+++ b/stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt	(date 1656490731575)
@@ -252,6 +252,9 @@
 
     private fun sendMessageInternal(message: Message) {
         val (channelType, channelId) = cid.cidToTypeAndId()
+        ChatLogger.get("RafalTest")
+            .logE("Before send. Id: ${message.id} \n MentionedUser: ${message.mentionedUsers.firstOrNull()?.id}" +
+                "\n MentionedUserId: ${message.mentionedUsersIds.firstOrNull()}")
         chatClient.sendMessage(channelType, channelId, message)
             .enqueue(
                 onError = { chatError ->
Index: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt b/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
--- a/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt	(revision ec47876a396b3377fec5ff3f6dad4776b215da6b)
+++ b/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt	(date 1656490731575)
@@ -44,6 +44,7 @@
 import com.getstream.sdk.chat.viewmodel.messages.MessageListViewModel
 import io.getstream.chat.android.client.ChatClient
 import io.getstream.chat.android.client.call.Call
+import io.getstream.chat.android.client.logger.ChatLogger
 import io.getstream.chat.android.client.models.Attachment
 import io.getstream.chat.android.client.models.Channel
 import io.getstream.chat.android.client.models.Flag
@@ -1013,6 +1014,17 @@
      * the message list.
      */
     public fun displayNewMessages(messageListItemWrapper: MessageListItemWrapper) {
+        with(messageListItemWrapper.items) {
+            if (isNotEmpty()) {
+                val messageItem = last()
+                if (messageItem is MessageListItem.MessageItem) {
+                    val message = messageItem.message
+                    ChatLogger.get("RafalTest")
+                        .logE("After send. Id: ${message.id} \n MentionedUser: ${message.mentionedUsers.firstOrNull()?.id}" +
+                            "\n MentionedUserId: ${message.mentionedUsersIds.firstOrNull()}")
+                }
+            }
+        }
         buffer.enqueueData(messageListItemWrapper)
     }
 
```
</details>

1. Filter logcat by `RafalTest`. The patch adds two logs (before and after sending the message)
2. Send a message with attachments and mention
3. Observe logs. Before sending the message you should see `     MentionedUser: null
     MentionedUserId: filip` and after sending the message `     MentionedUser: filip
     MentionedUserId: null`

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] Bugs validated (bugfixes)
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### CODE REVIEW

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt [hunk 1]
```diff
@@ -89,7 +90,8 @@ internal fun Message.toEntity(): MessageEntity = MessageEntity(
         reactionCounts = reactionCounts,
         reactionScores = reactionScores,
         shadowed = shadowed,
-        mentionedUsersId = mentionedUsers.map(User::id),
+        mentionedUsers = mentionedUsers.map(User::id),
+        mentionedUsersId = mentionedUsersIds,
```
Comment (kanat) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt:94]: Hey @adasiewiczr,

I've tested your patch and it works as expected.
However I wonder if we can do something like this:
```kotlin
mentionedUsersId = when (mentionedUsers.isNotEmpty()) {
    true -> mentionedUsers.map(User::id)
    else -> mentionedUsersIds
}
```

To avoid having in DB a more or less duplicate column.

Comment (kanat) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt:94]: Makes sense.
Do you think it's possible to rename `mentionedUsers` to something `remoteMentionedUserIds`?

The first time you look at `mentionedUsers` you would expect to see `users` and not `userIds` again.

**Review by kanat — APPROVED** [review]
LGTM.

Works as expected.
