### PR TITLE
Fix/push notification

### LINKED ISSUE #578: Add a method to identify streamchat related notifications
As we already have a `FirebaseMessagingService` implementation, which handles a lot of different types of push notifications, we cannot directly add your `ChatFirebaseNotificationService` to the manifest. Instead, we need to be able to determine which type of push message it is, and then call the appropriate handler.

A common pattern for this on Android (e.g. intercom and others) is to provide a `isStreamChatMessage: Boolean` method, which we can use to then call `Client.onMessageReceived()`.

gz#4564

### PR DESCRIPTION
**Pull request by JcMinarro**
Fixes #578
### Description
Add method to know if a RemoteMessage is valid for Stream
Fix crash when a push notification arrives from another provider different than Stream

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [x] Changelog updated with client-facing changes
- ~[ ] New code is covered by unit tests~
- ~[ ] Comparison screenshots added for visual changes~
- [x] Reviewers added

### CODE REVIEW

File: stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt [hunk 1]
```diff
@@ -927,5 +935,8 @@ public class ChatClient internal constructor(
 
         public val isInitialized: Boolean
             get() = instance != null
+
+        public fun isValid(remoteMessage: RemoteMessage, defaultNotificationConfig: NotificationConfig = NotificationConfig()): Boolean =
```
Comment (adasiewiczr) [inline stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt:939]: NIT: I think it might be worth it to give all `isValid` methods  (except RemoteMessage extension function)  a more descriptive name, e.g. `isValidRemoteMessage`. What do you think?

File: stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatFirebaseMessagingService.kt [hunk 2]
```diff
@@ -1,19 +1,65 @@
...
+
+    private fun createSyncNotificationChannel() {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
+            NotificationChannel(CHANNEL_ID, CHANNEL_NAME, NotificationManager.IMPORTANCE_HIGH).run {
+                getSystemService(NotificationManager::class.java).createNotificationChannel(this)
+            }
+        }
+    }
+
+    companion object {
```
Comment (adasiewiczr) [inline stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatFirebaseMessagingService.kt:60]: This can probably be private

**Review by adasiewiczr — APPROVED** [review]

File: UNRELEASED_CHANGELOG.md [hunk 3]
```diff
@@ -10,6 +10,8 @@
     - 24 vs 12 hr controlled by user's System settings.
 
 ## stream-chat-android-client
+- Add method to know if a RemoteMessage is valid for Stream
```
Comment (zsmb13) [inline UNRELEASED_CHANGELOG.md:13]: Would be useful to name the specific class/method here

File: stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/RemoteMessageExtensions.kt [hunk 4]
```diff
@@ -0,0 +1,12 @@
+package io.getstream.chat.android.client.extensions
+
+import com.google.firebase.messaging.RemoteMessage
+import io.getstream.chat.android.client.notifications.handler.NotificationConfig
+
+public fun RemoteMessage.isValid(notificationConfig: NotificationConfig): Boolean =
```
Comment (zsmb13) [inline stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/RemoteMessageExtensions.kt:6]: Do we want to provide this as separate public API, shouldn't checks just go through `ChatClient`'s companion?

Having gone through all the code on this PR, it looks like we have... Five (?) public methods for checking if a message is valid now. Do we really need to expose all of these?

**Review by adasiewiczr — APPROVED** [review]

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt [hunk 5]
```diff
@@ -155,18 +155,15 @@ public interface ChatDomain {
             return this
         }
 
-        // TODO: do we even need this, or is it better to have it at the low level client?
+        @Deprecated("This method is deprecated, you should configure it into the ChatClient")
         public fun notificationConfig(notificationConfig: NotificationConfig): Builder {
-            this.notificationConfig = notificationConfig
+            ChatLogger.get("ChatDomain").logE("This method is deprecated, you should configure it into the ChatClient")
```
Comment (zsmb13) [inline stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt:160]: This method can still be called, but it's now a silent no-op, which will be unexpected for clients. Perhaps we want to mark this as `level = ERROR` so that it breaks the build? And even then, I'd keep it functional if possible, until we remove it.

**Review by zsmb13 — CHANGES_REQUESTED** [review]

File: stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt (hunk 5 above)
Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt:160]: Yep, `level = ERROR` is the best way for now. Keep old behavior could give us some problem with a bad configuration

Comment (zsmb13) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt:163]: We might still have people who already have compiled code that calls into this method, but I guess it's gonna be rare. Maybe throw an exception for that case, so that this never gets silently executed?

Comment (JcMinarro) [reply stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt]: :+1:

**Review by zsmb13 — APPROVED** [review]

**Review by samiuelson — APPROVED** [review]
