### PR TITLE
Close Gallery if the list of pictures to show is empty

### LINKED ISSUE #1959: [Crash][AttachmentGalleryActivity] Empty list doesn't contain element at index 0.
Crashlytics logs indicate that Application was just launched when the issue occurs. So, I believe, user paused on AttachmentGalleryActivity, and something like process death happens.

Following is the stack trace I received:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
       at kotlin.collections.EmptyList.get(Collections.kt:36)
       at kotlin.collections.EmptyList.get(Collections.kt:24)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.onGalleryPageSelected(AttachmentGalleryActivity.kt:157)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.observePageChanges(AttachmentGalleryActivity.kt:139)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.setupGallery(AttachmentGalleryActivity.kt:86)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.access$setupGallery(AttachmentGalleryActivity.kt:36)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$onCreate$2.invoke(AttachmentGalleryActivity.kt:78)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$onCreate$2.invoke(AttachmentGalleryActivity.kt:36)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$sam$androidx_lifecycle_Observer$0.onChanged(:2)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
       at android.app.Activity.dispatchActivityPostStarted(Activity.java:1278)
       at android.app.Activity.performStart(Activity.java:8018)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

v4.10.0

### PR DESCRIPTION
**Pull request by JcMinarro**
### 🎯 Goal
Close AttachmentGalleryActivity in case no attachment are received.
Fix #1959 

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- ~[ ] Changelog is updated with client-facing changes~
- ~[ ] New code is covered by unit tests~
- ~[ ] Comparison screenshots added for visual changes~
- ~[ ] Affected documentation updated (CMS, cookbooks, tutorial)~
- [x] Reviewers added

### CODE REVIEW

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt [hunk 1]
```diff
@@ -81,11 +81,15 @@ public class AttachmentGalleryActivity : AppCompatActivity() {
     }
 
     private fun setupGallery(attachmentGalleryItems: List<AttachmentGalleryItem>) {
-        this.attachmentGalleryItems = attachmentGalleryItems
-        setupGalleryAdapter()
-        setupShareImageButton()
-        setupAttachmentActionsButton()
-        observePageChanges()
+        if (attachmentGalleryItems.isEmpty()) {
```
Comment (ogkuzmin) [inline stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt:84]: Strange that it's possible to open gallery when a collection is empty

**Review by ogkuzmin — APPROVED** [review]

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt (hunk 1 above)
Comment (bychkovdmitry) [reply stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt:84]: @ogkuzmin Probably empty after process death

**Review by bychkovdmitry — APPROVED** [review]

File: stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt (hunk 1 above)
Comment (JcMinarro) [reply stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt:84]: Yep, it happens because we are not adding attachments to the bundle (The list could be so big)
Normally a user will open the gallery, interact with it and close it. Event if they leave the app and open again, if the system didn't kill the process, they will be able to see the full gallery again. In another case, close the gallery I think is the easy and fast fix for it
