### PR TITLE
Fix/Channellist Last Message for Attachment

### LINKED ISSUE #240: Channel List has null text if the last message is an attachment

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request
close #240

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java [hunk 1]
```diff
@@ -117,52 +102,127 @@ public void bind(Context context, ChannelState channelState, int position) {
...
+        });
+    }
 
-        if (lastMessage != null) {
-            // set the lastMessage and last messageDate
+    @SuppressLint("ResourceType")
+    private void configLastMessage(ChannelState channelState){
+        Message lastMessage = channelState.getLastMessage();
+        iv_attachment_type.setVisibility(View.GONE);
+        // null check
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java]: The comment seems is too obvious, so useless.

File: library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java [hunk 2]
```diff
@@ -117,52 +102,127 @@ public void bind(Context context, ChannelState channelState, int position) {
...
+        @IdRes int attachmentType;
+
+        switch (attachment.getType()) {
+            case ModelType.attach_image:
+                lastMessageText = "photo";
+                attachmentType = R.drawable.stream_ic_image;
+                break;
+            case ModelType.attach_file:
+                if (attachment.getMime_type() != null && attachment.getMime_type().contains("video")){
+                    lastMessageText = "video";
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java]: These tests should be extracted into `strings.xml`

File: library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java (hunk 1 above)
Comment (elevenetc) [reply library/src/main/java/com/getstream/sdk/chat/adapter/ChannelListItemViewHolder.java]: And the same about other similar comments.
