### PR TITLE
fixes tons of edge case bugs with sending messages offline and reconn…

### LINKED ISSUE #101: MessageInputView stuck in disabled state after failed send
After sending a message while having poor/none connection, the MessageInputView gets stuck in a state where you cannot send any more text messages.
Clearing the textfield, editing it, resending the failed message or establishing a good connection doesn't fix it
Screenshot_20191007-104700__01

### PR DESCRIPTION
**Pull request by tbarbugli**
- Handle resending message better (make sure we don't get dupes or failed messages stuck)
- Remove the ugly "Waiting for connection" message from message list (it was also pretty broken and hard to customize [too many layers])
- Added a "Waiting for connection..." live message to channel header (easy to customize it via styles and by subclassing the view)

image

- Fixes one regression with failed messages blocking message input forever (fixes #101)

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/rest/Message.java [hunk 1]
```diff
@@ -129,6 +127,16 @@
...
+    public boolean isInflight() {
+        return inflight;
+    }
+
+    public void setInflight(boolean inflight) {
+        this.inflight = inflight;
+    }
+
+    private boolean inflight = false;
+
```
Comment (tschellenbach) [inline library/src/main/java/com/getstream/sdk/chat/rest/Message.java]: how is this different from the message sync status? looks identical

File: library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderViewStyle.java [hunk 2]
```diff
@@ -50,6 +51,7 @@ public ChannelHeaderViewStyle(Context c, AttributeSet attrs) {
         lastActiveTextSize = (int) a.getDimension(R.styleable.ChannelHeaderView_streamChannelHeaderLastActiveTextSize, getDimension(R.dimen.stream_channel_preview_date));
         lastActiveTextColor = a.getColor(R.styleable.ChannelHeaderView_streamChannelHeaderLastActiveTextColor, getColor(R.color.stream_gray_dark));
         lastActiveTextStyle = a.getInt(R.styleable.ChannelHeaderView_streamChannelHeaderLastActiveTextStyle, Typeface.NORMAL);
+        offlineText = a.getString(R.styleable.ChannelHeaderView_streamChannelHeaderOfflineTextStyle);
```
Comment (adrian09h) [inline library/src/main/java/com/getstream/sdk/chat/view/ChannelHeaderViewStyle.java]: `ChannelHeaderView_streamChannelHeaderOfflineTextStyle` looks weird name.
Why doesn't it have `ChannelHeaderView_streamChannelHeaderOfflineText`?
