### PR TITLE
Feature/Fix giphy editing issue

### LINKED ISSUE #172: Editing giphy message converts message into text message
Editing `gyphy` message converts message into text message. Also when editing suggests to edit empty text field.

See video: https://drive.google.com/file/d/1WAZKM57TUvWxsPZObkxhVXt1_XZn2uCz/view?usp=sharing

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request

- fix bug for Editing giphy message.
close #172 

- before

- after

### CODE REVIEW

File: library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java [hunk 1]
```diff
@@ -489,9 +491,20 @@ private void onSendMessage(String input, boolean isEdit) {
...
         if (isEdit) {
-            getEditMessage().setText(input);
-            getEditMessage().setAttachments(messageInputClient.getSelectedAttachments());
-            viewModel.getChannel().updateMessage(getEditMessage(),  new MessageCallback() {
+            Message message = getEditMessage();
+            message.setText(input);
+            if (messageInputClient.getSelectedAttachments() != null
+                    && !messageInputClient.getSelectedAttachments().isEmpty()){
+                List<Attachment>attachments = message.getAttachments();
+                for (Attachment attachment : messageInputClient.getSelectedAttachments()){
```
Comment (elevenetc) [inline library/src/main/java/com/getstream/sdk/chat/view/MessageInputView.java]: By extracting `messageInputClient.getSelectedAttachments()` once  readability could be improved.

**Comment by tbarbugli** [comment]
@adrian09h can you attach a video of the new behavior?

**Comment by adrian09h** [comment]
> @adrian09h can you attach a video of the new behavior?

Will soon. ;)
